apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: process-fbc
spec:
  params:
  - name: branch
    type: string
  - name: SECRET_NAME
    default: rhoai-konflux-secret
    type: string
  - name: CLUSTER
    default: rh01
    type: string
  - name: pipelinerun-name
    description: pipeline-run to annotate
  steps:
    - name: process-fbc-fragment
      image: quay.io/rhoai/rhoai-task-toolset:latest
      env:
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: token
        - name: GH_USER
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: username
        - name: GH_PAT
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: pat
        - name: PIPELINERUN_NAME
          value: $(params.pipelinerun-name)
        - name: BRANCH
          value: $(params.branch)
      script: |
        #!/bin/bash
        
        #Declare basic variables
        OPENSHIFT_VERSION=v4.13
        RHOAI_VERSION=v${BRANCH/rhoai-/}
        COMPONENT_SUFFIX=${RHOAI_VERSION/./-}
        RBC_REPO_URL="github.com/red-hat-data-services/RHOAI-Build-Config.git"
        UTILS_REPO_URL="github.com/rhoai-rhtap/fbc-utils.git"
        
        OC_TOKEN=$(echo $OC_TOKEN | awk '{$1=$1};1' | tr -d '\n')
        GH_USER=$(echo $GH_USER | awk '{$1=$1};1' | tr -d '\n')
        GH_PAT=$(echo $GH_PAT | awk '{$1=$1};1' | tr -d '\n')
        
        #check the playpen
        echo "current dir $(pwd)"
        echo "contents $(ls -l)"
        echo "cloning the main branch to main dir"
        
        echo "GH_USER = $GH_USER"
        
        #Clone all the required repos
        git clone "https://${GH_USER}:${GH_PAT}@${RBC_REPO_URL}" --branch=main main
        git clone "https://${GH_USER}:${GH_PAT}@${RBC_REPO_URL}" --branch=$(params.branch) $(params.branch)
        git clone "https://${GH_USER}:${GH_PAT}@${UTILS_REPO_URL}" utils
        
        #Declare FBC processing variables
        CATALOG_YAML_PATH=main/catalog/${OPENSHIFT_VERSION}/rhods-operator/catalog.yaml
        PATCH_YAML_PATH=$(params.branch)/catalog/catalog-patch.yaml
        SINGLE_BUNDLE_PATH=latest_bundle.yaml
        OUTPUT_CATALOG_PATH=$(params.branch)/catalog/${OPENSHIFT_VERSION}/rhods-operator/catalog.yaml
        
        #Generate the catalog for the latest bundle
        API_SERVER=""
        oc
        
        if [[ $(params.CLUSTER) == 'rh01' ]]
        then
          API_SERVER="https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'm01' ]]
        then 
          API_SERVER="https://api.stone-prd-m01.84db.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'p02' ]]
        then
          API_SERVER="https://api.stone-prod-p02.hjvn.p1.openshiftapps.com:6443"
        fi
        
        
        
        echo "API_SERVER = ${API_SERVER}"
        
        oc login --token="${OC_TOKEN}" --server=${API_SERVER}
        
        echo "pipelinerun = ${PIPELINERUN_NAME}"
        oc get pipelinerun ${PIPELINERUN_NAME}
        APPLICATION_NAME=$(oc get pipelineruns -n rhoai-tenant ${PIPELINERUN_NAME} -o json | jq -r '.metadata.labels."appstudio.openshift.io/application"')
        echo "APPLICATION_NAME = $APPLICATION_NAME"
        LATEST_SNAPSHOT=$(oc get snapshots -l "pac.test.appstudio.openshift.io/event-type in (push, Push),appstudio.openshift.io/application=${APPLICATION_NAME}" --sort-by=.metadata.creationTimestamp | tail -1 | awk '{print $1}')
        echo "LATEST_SNAPSHOT = ${LATEST_SNAPSHOT}"
        
        echo "component-suffix = $COMPONENT_SUFFIX"
        
        
        
        #Invoke the FBC processor
        pip install -r utils/fbc-processor/requirements.txt
        python3 utils/fbc-processor/fbc-processor.py ${CATALOG_YAML_PATH} ${PATCH_YAML_PATH} ${SINGLE_BUNDLE_PATH} ${OUTPUT_CATALOG_PATH}
        cat ${OUTPUT_CATALOG_PATH}
        
        #Push the changes to the release branch
        #cd $(params.branch)
        #git add .
        #git status
        #git commit -m "updating the latest FBC catalog.yaml to the release branch"
        #git push -u origin $(params.branch)