apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: process-fbc
spec:
  params:
  - name: branch
    type: string
  - name: rhoai-version
    type: string
  - name: component-suffix
    default: "{{hyphenize .rhoai-version}}"
    type: string
  - name: bundle-component-name
    type: string
  - name: SECRET_NAME
    default: rhoai-konflux-secret
    type: string
  - name: CLUSTER
    default: rh01
    type: string
  - name: pipelinerun-name
    description: pipeline-run to annotate
  steps:
    - name: process-fbc-fragment
      image: quay.io/rhoai/rhoai-task-toolset:latest
      script: |
        #!/bin/bash
        
        #Declare basic variables
        OPENSHIFT_VERSION=v4.13
        RBC_REPO_URL="git@github.com:red-hat-data-services/RHOAI-Build-Config.git"
        UTILS_REPO_URL="git@github.com:rhoai-rhtap/fbc-utils.git"
        
        #check the playpen
        echo "current dir $(pwd)"
        echo "contents $(ls -l)"
        echo "cloning the main branch to main dir"
        
        #Clone all the required repos
        git clone ${RBC_REPO_URL} --branch main main
        git clone ${RBC_REPO_URL} --branch $(params.branch) $(params.branch)
        git clone ${UTILS_REPO_URL} utils
        
        #Declare FBC processing variables
        CATALOG_YAML_PATH=main/catalog/${OPENSHIFT_VERSION}/rhods-operator/catalog.yaml
        PATCH_YAML_PATH=$(params.branch)/catalog/catalog-patch.yaml
        SINGLE_BUNDLE_PATH=latest_bundle.yaml
        OUTPUT_CATALOG_PATH=$(params.branch)/catalog/${OPENSHIFT_VERSION}/rhods-operator/catalog.yaml
        
        #Generate the catalog for the latest bundle
        API_SERVER=""
        oc
        
        if [[ $(params.CLUSTER) == 'rh01' ]]
        then
          API_SERVER="https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'm01' ]]
        then 
          API_SERVER="https://api.stone-prd-m01.84db.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'p02' ]]
        then
          API_SERVER="https://api.stone-prod-p02.hjvn.p1.openshiftapps.com:6443"
        fi
        
        OC_TOKEN=$(echo $OC_TOKEN | awk '{$1=$1};1' | tr -d '\n')
        
        echo "API_SERVER = ${API_SERVER}"
        
        oc login --token="${OC_TOKEN}" --server=${API_SERVER}
        
        echo "pipelinerun = ${PIPELINERUN_NAME}"
        oc get pipelinerun ${PIPELINERUN_NAME}
        APPLICATION_NAME=$(oc get pipelineruns -n rhoai-tenant ${PIPELINERUN_NAME} -o json | jq -r '.metadata.labels."appstudio.openshift.io/application"')
        echo "APPLICATION_NAME = $APPLICATION_NAME"
        LATEST_SNAPSHOT=$(oc get snapshots -l "pac.test.appstudio.openshift.io/event-type in (push, Push),appstudio.openshift.io/application=${APPLICATION_NAME}" --sort-by=.metadata.creationTimestamp | tail -1 | awk '{print $1}')
        echo "LATEST_SNAPSHOT = ${LATEST_SNAPSHOT}"
        
        echo "component-suffix = $(params.component-suffix)"
        
        
        
        #Invoke the FBC processor
        pip install -r utils/fbc-processor/requirements.txt
        python3 utils/fbc-processor/fbc-processor.py ${CATALOG_YAML_PATH} ${PATCH_YAML_PATH} ${SINGLE_BUNDLE_PATH} ${OUTPUT_CATALOG_PATH}
        
        #Push the changes to the release branch
        #cd $(params.branch)
        #git add .
        #git status
        #git commit -m "updating the latest FBC catalog.yaml to the release branch"
        #git push -u origin $(params.branch)

    - name: hello
      image: quay.io/redhat-appstudio/task-toolset@sha256:5c6b5f9f5b3df5379e37d6f045d10910339c88ab19038ce7a78d414204b63cec
      script: |
        #!/bin/bash
        echo "Hello $(params.username)!"