apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: process-fbc
spec:
  params:
  - name: revision
    type: string
  - name: bundle-component-name
    type: string
  steps:
    - name: process-fbc-fragment
      image: quay.io/rhoai/rhoai-task-toolset:latest
      script: |
        #!/bin/bash
        
        #Declare basic variables
        OPENSHIFT_VERSION=v4.13
        RBC_REPO_URL="git@github.com:red-hat-data-services/RHOAI-Build-Config.git"
        UTILS_REPO_URL="git@github.com:rhoai-rhtap/fbc-utils.git"
        
        #check the playpen
        echo "current dir $(pwd)"
        echo "contents $(ls -l)"
        echo "cloning the main branch to main dir"
        
        #Clone all the required repos
        git clone ${RBC_REPO_URL} --branch main main
        git clone ${RBC_REPO_URL} --branch $(params.revision) $(params.revision)
        git clone ${UTILS_REPO_URL} utils
        
        #Declare FBC processing variables
        CATALOG_YAML_PATH=main/catalog/${OPENSHIFT_VERSION}/rhods-operator/catalog.yaml
        PATCH_YAML_PATH=$(params.revision)/catalog/catalog-patch.yaml
        SINGLE_BUNDLE_PATH=latest_bundle.yaml
        OUTPUT_CATALOG_PATH=$(params.revision)/catalog/${OPENSHIFT_VERSION}/rhods-operator/catalog.yaml
        
        #Generate the catalog for the latest bundle
        API_SERVER=""
        oc
        
        if [[ $(params.CLUSTER) == 'rh01' ]]
        then
          API_SERVER="https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'm01' ]]
        then 
          API_SERVER="https://api.stone-prd-m01.84db.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'p02' ]]
        then
          API_SERVER="https://api.stone-prod-p02.hjvn.p1.openshiftapps.com:6443"
        fi
        
        OC_TOKEN=$(echo $OC_TOKEN | awk '{$1=$1};1' | tr -d '\n')
        
        echo "secret = $(params.SECRET_NAME)"
        echo "token = ${OC_TOKEN}"
        echo "API_SERVER = ${API_SERVER}"
        
        oc login --token="${OC_TOKEN}" --server=${API_SERVER}
        oc get components -n rhoai-tenant
        
        
        #Invoke the FBC processor
        python3 utils/fbc-processor/fbc-processor.py ${CATALOG_YAML_PATH} ${PATCH_YAML_PATH} ${SINGLE_BUNDLE_PATH} ${OUTPUT_CATALOG_PATH}
        
        #Push the changes to the release branch
        cd $(params.revision)
        git add .
        git status
        git commit -m "updating the latest FBC catalog.yaml to the release branch"
        git push -u origin $(params.revision)

    - name: hello
      image: quay.io/redhat-appstudio/task-toolset@sha256:5c6b5f9f5b3df5379e37d6f045d10910339c88ab19038ce7a78d414204b63cec
      script: |
        #!/bin/bash
        echo "Hello $(params.username)!"