apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-custom-task
spec:
  params:
  - name: username
    type: string
  - name: SECRET_NAME
    default: rhoai-konflux-secret
    type: string
  - name: CLUSTER
    default: rh01
    type: string
  steps:
    - name: echo
      image: quay.io/redhat-appstudio/task-toolset@sha256:5c6b5f9f5b3df5379e37d6f045d10910339c88ab19038ce7a78d414204b63cec
      env:
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: token
      script: |
        #!/bin/bash
        API_SERVER=""
        
        OC_CLI_MIRROR="https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz"
        wget ${OC_CLI_MIRROR} 
        tar xvf openshift-client-linux.tar.gz
        chmod +x oc
        sudo mv oc /usr/local/bin/
        oc
        
        if [[ $(params.CLUSTER) == 'rh01' ]]
        then
          API_SERVER="https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'm01' ]]
        then 
          API_SERVER="https://api.stone-prd-m01.84db.p1.openshiftapps.com:6443"
        elif [[ $(params.CLUSTER) == 'p02' ]]
        then
          API_SERVER="https://api.stone-prod-p02.hjvn.p1.openshiftapps.com:6443"
        fi
        oc login --token="${OC_TOKEN}" --server=${API_SERVER}
        oc get components -n rhoai-tenant
        
        echo "starting the task"
        echo "Hello World!!!"
    - name: goodbye
      image: quay.io/redhat-appstudio/task-toolset@sha256:5c6b5f9f5b3df5379e37d6f045d10910339c88ab19038ce7a78d414204b63cec
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"