apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rhoai-tenant
  name: rhoai-sa-role
rules:
- apiGroups: [""]
  resources: ["applications", "component", "environment", "pods", "deployment", "deploymenttarget", "gitops", "pipelinerun", "pipelineresult",
  "integrationtestscenarios", "enterprisecontractpolicies"]
  verbs: ["get"]
