apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rhoai-tenant
  name: rhoai-sa-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["appstudio.redhat.com"]
  resources: ["applications", "components", "integrationtestscenarios", "enterprisecontractpolicies"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelines"]
  verbs: ["get", "watch", "list"]
